### PR TITLE
Fix for zooming & mobile nav / Safari bug fix

### PR DESCRIPTION
**Pull request by snowiewdev**
Fix for mobile nav, related to issues #29 , #28 
- increased input font-size to minimum 16px to prevent auto-zooming
- ui fix for mobile nav
- home hero ui update for copy update
- fix for safari bug overflow-hidden not working with border-radius
- dropped circular nav reveal animation due to ios not supporting clip-path on zoom-in

Test URLs:
- Before: https://main--tbx-intr--tbx-co.hlx.page/
- After: https://feature-about-and-contact--tbx-intr--tbx-co.hlx.page/

The issue may be related to Safari not supporting clip-path on zoom:
[https://developer.apple.com/forums/thread/733315](https://developer.apple.com/forums/thread/733315)
-> dropped the circular nav animation for the fix

### CODE REVIEW

**Comment by solomon71** [comment]
This behavior is seen on iOS Safari, Chrome, and Firefox. @snowiewdev iOS 17.1.2, latest version of apps.

**Comment by snowiewdev** [comment]
> 17.1.2

Thanks for the extra info. I think the issue is that the clip-path property is not well supported on ios currently. We may need to give up the circular reveal animation for the fix.

**Comment by solomon71** [comment]
OK, yes. Can we do a pretty quick fade-in fade-out animation for reveal and hide?

**Comment by snowiewdev** [comment]
dropped circular nav animation as `clip-path` not well-supported on ios when zooming in
replaced with simple fade animation

**Pull request merged**
